apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment
  template:
    metadata:
      labels:
        app: sentiment
    spec:
      containers:
        - name: sentiment
          image: onurceylan7/sentiment-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
